### ISSUE TITLE
Changement de nom de domaine

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#1213]
# Phase 1

- [ ] Rediriger le nouveau domaine vers nos serveurs @mmagn
- [ ] Rediriger les variantes du nouveau domaine vers le nouveau domaine @mmagn
- [ ] Acheter et configurer le certificat SSL du nouveau domaine @lesim
- [ ] Configurer les mailing-lists sur le nouveau domaine @gregoirenovel
- [ ] Configurer Mailjet pour le nouveau domaine @gregoirenovel
- [ ] Configurer HelpScout pour la nouvelle adresse de contact @gregoirenovel
- [x] Envoyer un email préventif aux administrateurs, appel à remarques et observations (whitelisting des mails) @gregoirenovel

# Phase 2

- [ ] Mettre un bandeau sur le site qui annonce le futur changement de nom @gregoirenovel
- [ ] Envoyer un mail à tout le monde qui informe du futur changement de nom avec une date précise

# Phase 3

- [ ] Changer le wording dans les CGU
- [ ] Rediriger la vieille adresse email contact vers la nouvelle adresse email contact
- [ ] Changer HelpScout (signatures, adresse email)
- [ ] Changer Mailjet
- [ ] Changer le wording dans GitBook ainsi que le nom du projet
- [ ] Rediriger l'ancien nom de domaine vers le nouveau (en conservant la seconde partie de l'URL)
- [ ] Rediriger anciens mails vers nouveau mails
- [ ] Mettre en prod le site avec le nouveau wording
- [ ] Changer le nom du channel Slack
- [ ] Changer le repo Github et les liens associés

# Questions ?

- Est-ce qu'on affiche le bandeau qui informe du changement dans l'état connecté ?
