### ISSUE TITLE
ETQ Usager je veux renseigner mes informations SIRET dans la nouvelle UI

### ISSUE THREAD

**Issue by mmagn** [betagouv/tps#1410]
Implémenter les écrans d'informations SIRET dans la nouvelle interface utilisateur (plutôt que dans l'ancienne).

**TODO**

- [x] Implémenter la page d'entrée du n° SIRET
- [x] Implémenter la page de validation des infos
- [x] Peinture
- [x] Afficher la carto au besoin
- [x] Tests
- [x] Supprimer l'ancien code

**Comment by kemenaran** [comment]
## Mockups

**Page initiale** (en suivant un lien `/commencer`)

<img width="1056" alt="capture d ecran 2018-10-04 a 12 03 47" src="https://user-images.githubusercontent.com/179923/46467862-23f1b180-c7cf-11e8-8f0c-d4989dac4876.png">

https://wireframe.cc/vTrctz

**Page de vérification des infos SIRET**

<img width="1062" alt="capture d ecran 2018-10-04 a 12 14 22" src="https://user-images.githubusercontent.com/179923/46467836-13413b80-c7cf-11e8-9e70-07f2b1cf8d20.png">

https://wireframe.cc/RFug2D

Quand on clique sur "Continuer", on arrive sur la carto (ou sur le formulaire).
