### ISSUE TITLE
Créer une page de garde pour les démarches

### ISSUE THREAD

**Issue by gregoirenovel** [betagouv/tps#2225]
Aujourd'hui, les liens "/commencer" redirigent directement vers un formulaire de connexion (ou de SIRET).

On devrait plutôt afficher une "page de garde" de la démarche, avec :

- des infos sur la démarche
- un bouton "Commencer"
- éventuellement un bouton pour récupérer un brouillon existant

Ça permettrait :

- d'avoir plus de place pour afficher des infos claires
- éviter une redirection automatique
- avoir des pages indexables par Google

## TODO

- [x] Mockups
- [x] Mutualiser le layout de la page "commencer" (#3180)
- [x] Adapter la page sign_in à ce layout partagé (#3259)
- [x] Créer une page autonome pour "Commencer"
- [x] Layout de la page "Commencer" non-connectée
- [x] Layout de la page "Commencer" connectée :
  - [x] Aucun dossier
  - [x] Un brouillon
  - [x] Un dossier déposé
  - [x] Plusieurs dossiers
- [x] Rediriger vers /commencer après le sign-in et le sign-up
- [x] Amélioration du layout mobile
- [x] Tests

**Comment by chaibax** [comment]
Pensez à ajouter  <meta name="robots" content="noindex"> dans le <head>

**Comment by gregoirenovel** [comment]
@chaibax à ajouter dans le quoi ?

**Comment by chaibax** [comment]
Je ne pense pas que ce soit une bonne idée que ces pages soient indexable par Google. 

Ce sont aux admins de communiquer le lien *sur leur site*. C'est mieux comme ça, car ils peuvent y mettre les infos souhaitées et nécessaires. 

Cette page ne devrait pas être la landing de la démarche depuis Google. C'est la page contenant le lien vers la démarche sur le site de l'administration qui devrait sortir en 1er . Pas la nôtre. 

Enfin, on va faciliter l'arrivé depuis Google d'usager sur une démarche, alors qu'on est absolument pas sur ce que soit la bonne administration derrière (ex : neph pour un mauvais département) .

**Comment by gregoirenovel** [comment]
J'ai pas mal de remarques sur ces mockups (j'ai pas mal de brouillons qui trainent bossés cet été avec Clémence), on en parle IRL la semaine prochaine ?

**Comment by kemenaran** [comment]
@gregoirenovel yep, chaud pour en discuter – c'est justement l'idée derrière "faire les mockups avant de coder".

Si on arrive pas à se voir IRL, par écrit ou par annotation visuelle ça me va aussi.

**Comment by chaibax** [comment]
Je ne sais pas si c'est le cas, mais  pense qu'on ne devrait pas mettre de lien dans Herder de la page vers la home de DS. Je pense qu'on peut aussi enlever notre logo (ou mettre celui de l'administration qui propose la démarche, mais ca pose des soucis de format).

**Comment by gregoirenovel** [comment]
> Je pense qu'on peut aussi enlever notre logo

Pour moi ça touche à la vision qui n'est pas tranchée ça (marque blanche)

**Comment by Benjamin-Doberset** [comment]
Une question : pour "Page de garde - pas connecté" pourquoi laisse-t-on l'onglet dossier en haut? puisqu'on ne sait rien sur l'usager vu qu'il n'est pas connecté.

**Comment by kemenaran** [comment]
> Une question : pour "Page de garde - pas connecté" pourquoi laisse-t-on l'onglet dossier en haut? puisqu'on ne sait rien sur l'usager vu qu'il n'est pas connecté.

Par erreur de ma part :) Je vais supprimer ça des mockups.

> Pareil pourquoi laisse-t-on deux moyens de se connecter (un en haut à droite, un au centre)?

Mmm, dans ma tête c'est parce que :

- c'est raisonnable d'avoir toujours un bouton "Se connecter" en haut à droite, sur la plupart des pages ;
- au moment où on est _sûrs_ que l'utilisateur va vouloir se connecter, ça se fait de mettre un rappel en super-grand-et-bleu "SE CONNECTER !"

J'ai l'impression que généralement c'est plutôt une bonne pratique de mettre les actions là où l'utilisateur s'y attend – même si ça signifie les mettre à plusieurs endroits différents.
